### ISSUE TITLE
Error while running tests using waitForAction

### ISSUE THREAD

**Issue by danielmariz** [keajs/kea-waitfor#10]
Hi, my project is setup using CRA and Typescript and I'm getting this error while trying to write unit test for some listeners and have no idea how I can get this sorted in the configurations

```   
ReferenceError: regeneratorRuntime is not defined

      24 |         requestAuthentication(credentialsMock)
      25 |         expect(authLogic.values.isAuthenticating).toBe(true)
    > 26 |         const { value } = await waitForAction(authLogic.actions.authenticationFailed)
         |                                 ^
```

Also, is it possible to test if another function was called despite the actions inside a listener?

Cheers

**Comment by danielmariz** [comment]
What I am trying to test is this piece of code
`listeners: ({ actions }) => ({
        requestAuthentication: async ({ credentials }) => {
            //This only calls the authentication that's handle as a redirect page
            try {
                await authorizeUser(credentials); //TEST IF WAS CALLED      
            } catch (error) {
                actions.authenticationFailed(error) //TEST FORCING AN ERROR AND CHECK IF WAS CALLED
            }
        },`

**Comment by danielmariz** [comment]
And also will need to test this
```
urlToAction: ({ actions }) => ({
        '/auth/callback': (pathname:string, search:any, hash:any) => {        
            if(hash?.error){
                actions.authenticationFailed(hash as Auth0Error) //TEST IF WAS CALLED
                return
            }
            actions.requestUserData() //TEST IF WAS CALLED
        },
    }),
```

**Comment by danielmariz** [comment]
> Hi, my project is setup using CRA and Typescript and I'm getting this error while trying to write unit test for some listeners and have no idea how I can get this sorted in the configurations
> 
> ```
> ReferenceError: regeneratorRuntime is not defined
> 
>       24 |         requestAuthentication(credentialsMock)
>       25 |         expect(authLogic.values.isAuthenticating).toBe(true)
>     > 26 |         const { value } = await waitForAction(authLogic.actions.authenticationFailed)
>          |                                 ^
> ```
> 
> Also, is it possible to test if another function was called despite the actions inside a listener?
> 
> Cheers

To fix it I had do install
react-app-polyfill and import it under my setupTest like that:
`import "react-app-polyfill/stable";`

**Comment by mariusandra** [comment]
Hey, can you show the relevant part of code that initializes the plugins via `resetContext` for the tests?

**Comment by danielmariz** [comment]
sure, I don't do any special configuration, should I?
```
beforeEach(() => {
        resetContext({ 
            createStore: true,
            plugins: [
                waitForPlugin, 
                routerPlugin
            ]
        });
    });
```

**Comment by danielmariz** [comment]
Still waiting for a feedback over this

**Comment by mariusandra** [comment]
I think the problem here is that:

```js
// this line fires two events:
// 1) `push`, which immediately triggers the `urlToAction` listener that then dispatches 
// 2) `requestUserData`
router.actions.push('/auth/callback')

// the action was already fired before reaching this line, so we wait forever
const {value} = await waitForAction(authLogic.actions.requestUserData)
```

There are two ways that I can come up with to get around it.

First, run both in parallel:

```js
const [{ value }] = await Promise.all([
  waitForAction(authLogic.actions.requestUserData),
  () => router.actions.push('/auth/callback')
])
```

However I'm not 100% sure if they will always run in the same order. You may need to delay the push until the waitFor is ready, for example with:

```js
const [{ value }] = await Promise.all([
  waitForAction(authLogic.actions.requestUserData),
  () => setImmediate(() => router.actions.push('/auth/callback')) // or setTimeout?
])
```

... though it might not be needed.

The other option is to create some redux-middleware that logs all actions:

```js
const actions = []
resetContext({ 
    createStore: {
        middleware: [
            store => next => action => {
                actions.push(action)
                next(action)
            }
        ]
    },
    plugins: [
        waitForPlugin, 
        routerPlugin
    ]
});

// somewhere later
router.actions.push('/auth/callback')
expect(actions[actions.length - 1].type).toEqual(logic.actionTypes.requestUserData)
```

Hope this helps and apologies for the wait :)

**Comment by mariusandra** [comment]
There's a new kea test utils package out that makes this so much easier: https://kea.js.org/docs/guide/testing

**Comment by danielmariz** [comment]
thats cool cheers
