### ISSUE TITLE
wait for a selector value to change in between actions

### ISSUE THREAD

**Issue by danielmariz** [keajs/kea-waitfor#13]
Is it possible to test a reducer value in between actions trigged by listener actions?

`
const logic = kea({
    actions:  {
        requestUpdate: true,
        updateFailed: true,
        update: true,
    },
    reducers:  {
        isUpdating: [
            false,
            {
                requestUpdate: () => true,
                updateFailed: () => false,
                update: () => false,
            }
        ],
    },
    listeners: ({ actions }) => ({
        requestUpdate: async () => {
            try {
                const {payload} = await promiseExample()
                actions.updateUserProfile(payload)
            } catch (error) {
                actions.userUpdateFailed(error.message)
            }
        },
    }
})

const unmount = logic.mount()
const {isUpdating} = logic.values
expect(isUpdating).toBe(false) //WORKS AS EXPECTED
logic.actions.requestUpdate()
//THIS IS EXPECTED AS TRUE BEFORE THE update action is triggered inside the listener
expect(isUpdating).toBe(true) //FAILS
//WORKS AS EXPECTED
expect(promiseExample).toBeCalled()
const {value} = await waitForAction(update)
expect(value).toBe(true)
expect(isUpdating).toBe(false) 

`

**Comment by mariusandra** [comment]
Hey, I think the new kea test utils package will help with this: https://kea.js.org/docs/guide/testing
