### ISSUE TITLE
waitForPlugin is not a function

### ISSUE THREAD

**Issue by chapterjason** [keajs/kea-waitfor#3]
Hello, 

I get `App.tsx:62 Uncaught TypeError: kea_waitfor_1.waitForPlugin is not a function` if I try to register it like in the documentation.

We should change the documentation or change the plugin to export a function instead of the plugin object itself.

I would change the plugin to be consistent in the plugins, it also could be that the plugin will have some options in the future.

**Comment by mariusandra** [comment]
It's a function now, thanks for raising this!
